### ISSUE TITLE
PHP Warning:

### ISSUE THREAD

**Issue by kenny-nt** [crstauf/query-monitor-extend#35] opened 2021-11-03 09:00 UTC
```
wp-includes/formatting.php:1098
   wp_check_invalid_utf8()
wp-includes/formatting.php:4479
   esc_html()
wp-content/plugins/query-monitor-extend/output/html/constants.php:54
   do_action('shutdown')
wp-includes/load.php:1097
   shutdown_action_hook()
Unknown location



```

**Comment by crstauf** [comment] 2021-11-03 13:24
@khanh-nt Please provide the warning in full; as it stands this is not helpful.

**Comment by kenny-nt** [comment] 2021-11-03 16:19
```
Array to string conversion
wp-includes/formatting.php:1098
   wp_check_invalid_utf8()
wp-includes/formatting.php:4479
   esc_html()
wp-content/plugins/query-monitor-extend/output/html/constants.php:54
   do_action('shutdown')
wp-includes/load.php:1097
   shutdown_action_hook()
Unknown location
```
As I saw in Query Monitor just like that. The warning message is: Array To String Conversion.

**Comment by crstauf** [comment] 2021-12-12 00:13
Possible solution: check if value is scalar, and if not, use `var_export()`.

**Comment by crstauf** [comment] 2021-12-12 03:27
@khanh-nt Please try branch `issue/35` and confirm solves this issue.

**Comment by kenny-nt** [comment] 2021-12-27 09:17
```
[STDERR] PHP Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /public_html/wp-content/plugins/query-monitor-extend/image-sizes/qmx-image-sizes-collector.php:153
Stack trace:
```
New fatal error. Logged in > no error, guest > fatal error

**Comment by crstauf** [comment] 2021-12-29 01:22
@khanh-nt Please use branch `issue/35` as your testing branch.

**Comment by kenny-nt** [comment] 2021-12-29 11:21
Yes, I am using branch issue/35.
But Query Monitor have an update yesterday and Query Monitor Extend broke the site
If not login > it cause fatal error with both 1.2 version and issue/35 branch

**Comment by crstauf** [comment] 2021-12-29 16:01
@khanh-nt The file mentioned (`qmx-image-sizes-collector.php`) in [your previous comment](https://github.com/crstauf/query-monitor-extend/issues/35#issuecomment-1001457867) is not on the `issue/35` branch, indicating that you are not using `issue/35` branch. Can you please confirm you are testing on the proper branch?

**Comment by kenny-nt** [comment] 2021-12-29 17:08
Ya, have just checked. I am not on branch issue/35 for some sites. I will changed to issue/35 and report back asps

**Comment by kenny-nt** [comment] 2021-12-29 20:55
```
[209124] [T0] [STDERR] PHP Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /public_html/wp-content/plugins/query-monitor-extend/collectors/image_sizes.php:133
Stack trace:
#0 /public_html/wp-includes/class-wp-hook.php(305): QMX_Collector_Image_Sizes->filter__wp_get_attachment_image_src()
#1/public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters()
```

Have just delete and re-install branch issue/35:
If logged in > The front page load normally and if guest (no login) > Fatal Error

I have tried both of master and issue/35 > the same issue. We use PHP8.0.

**Comment by crstauf** [comment] 2021-12-29 23:42
Thanks for confirming, @khanh-nt.

This is a tricky thing to diagnose, because the second parameter is a property of [the `QMX_Collector_Image_Sizes` class](https://github.com/crstauf/query-monitor-extend/blob/master/collectors/image_sizes.php), which is [defined](https://github.com/crstauf/query-monitor-extend/blob/master/collectors/image_sizes.php#L14-L68) in [the `__construct()` method](https://github.com/crstauf/query-monitor-extend/blob/master/collectors/image_sizes.php#L12), and there's nothing to set it to `null` anywhere.

I could of course cast the property to `array`, but I'd rather figure out why the property is being set to `null` and solve that.

Is there any site where you're experiencing the issue that would be innocuous for me to play with and see the code directly involved, or is it trivial for you to spin up an environment for me to experiment on? Completely understandable if not, but if not I'll have to close this as unable to fix because I can't replicate it.

**Comment by kenny-nt** [comment] 2021-12-30 20:40
Do you have skype? I will give you login details for a site with that issue. (But as I test with all my sites > they are all fatal error...)

**Comment by crstauf** [comment] 2022-01-01 16:33
@khanh-nt I've a new idea that prevents the need to grant admin access anywhere. If you have identified that the source of the problem is the site theme, then please provide a zip file of the site theme, and I can test QMX with it. If it's a plugin, please indicate which plugin it is and I can test QMX with it. 🙂

**Comment by crstauf** [comment] 2022-01-19 05:00
Closing in favor of #43.

**Closed as completed by crstauf** 2022-01-19 05:00 UTC
